# Generated by Django 4.0 on 2021-12-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211223_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activation_key_expires',
            new_name='activation_key_expired',
        ),
    ]
